version: "3"
services:
  app:
    build: .
    labels:
      app: women-and-color-backend
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "1337:1337"
    networks:
      - web
    depends_on:
      - postgres
    env_file:
      - env/dev.env

  postgres:
    image: "postgres:9"
    networks:
      - web
    env_file:
      - env/dev.env


networks:
  web:
